### ISSUE TITLE
Linking.

### ISSUE THREAD

**Issue by deavmi** [majestrate/nntpchan#114]
Should I link the Debian 8 instructions from the building.md document and then remove the Debian stuff from there?

**Comment by majestrate** [comment]
no, i think it's good the way it is at the moment. no need to reorganize at the moment.

**Comment by deavmi** [comment]
K

On 20 June 2016 9:08:04 PM SAST, Jeff <notifications@github.com> wrote:
>no, i think it's good the way it is at the moment. no need to
>reorganize at the moment.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/majestrate/nntpchan/issues/114#issuecomment-227238785

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
