### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by deavmi** [majestrate/nntpchan#128]
Shouldn't the file `srnd.go` in this repo be renamed to NNTPChan as it is not the daemon but rather the interface that uses the daemon? And there is a repo for `srnd`?

**Comment by majestrate** [comment]
there is a repo for srnd see https://github.com/majestrate/srndv2

**Comment by deavmi** [comment]
But then surely the file srnd.go here should be renamed?

**Comment by majestrate** [comment]
actually I think that file is left over from an old experiment and isn't really needed anymore.

**Comment by deavmi** [comment]
Should you remove it then?

**Comment by majestrate** [comment]
probably

**Comment by deavmi** [comment]
Sounds good then. :+1:

**Comment by deavmi** [comment]
Maybe add it to .gitignore if you are not sure yet.

**Comment by majestrate** [comment]
the daemon's source tree has moved to this repo as of now-ish
