### ISSUE TITLE
I *need* this stuff please

### ISSUE THREAD

**Issue by faissaloo** [majestrate/nntpchan#133]
Please:

- Add pages to the overboard so it can be used in the same url format as every other board, or at least change it from just ukko to ukko-0 if you're going to limit it to one page.
- Please add a json version of the board list.  
  
I'm trying to write a client for NNTPchan and I *need* these features.

**Comment by majestrate** [comment]
so boards.json and paginated ukko?

**Comment by faissaloo** [comment]
Pretty much, but paginated ukko needs the same url format as other boards. Thank you.

**Comment by majestrate** [comment]
boards.json is simple, paginating ukko isn't since. I'll add boards.json but idk if ukko should be paginated. I'll give it a shot tho.

**Comment by majestrate** [comment]
added as of https://github.com/majestrate/srndv2/commit/262875116e9e1f7540cfa87f4387e9cf46002e3b

new json endpoints: 

/boards.json

/ukko-N.json (given N < 10 and N >= 0 )
