### ISSUE TITLE
Successful posting gives 200 OK

### ISSUE THREAD

**Issue by faissaloo** [majestrate/nntpchan#136]
It should be sending back 201 CREATED, this makes it hard to differentiate between an incorrect CAPTCHA and a successful post.

**Comment by majestrate** [comment]
try latest revision of backend, run `./build.sh`

**Comment by faissaloo** [comment]
I would but postgres is giving me a headache, I'm assuming you've already fixed this though? In that case, when will the fix be pushed to the nodes?

**Comment by majestrate** [comment]
the only meaningful change iirc was for this issue.

**Comment by faissaloo** [comment]
Can you get at least the biggest nodes to change over? Because right now not knowing if a CAPTCHA has gone through is a bit of a problem for the client I'm writing.

**Comment by majestrate** [comment]
Honestly if you can figure out how to get everyone to upgrade religiously that would help a LOT.
at the moment it's not a reasonable thing to ask of me since people are sticking to "working" revisions.

I can upgrade oniichan and/or 2hu but the others you'd have to figure out when they'll upgrade.

**Comment by faissaloo** [comment]
If 2hu and oniichan are updated that'd be good enough for me for now, I'll just go complain to the other node owners.

**Comment by majestrate** [comment]
both have been updated

**Comment by faissaloo** [comment]
That works, thank :+1:

**Comment by ctrlcctrlv** [comment]
>Honestly if you can figure out how to get everyone to upgrade religiously 

Botnet a la Microsoft obviously.

**Comment by majestrate** [comment]
adding an update hook may work but it adds centralization and needs to be opt in.

looks like this bug is fixed tho
