### ISSUE TITLE
spurious assert in srndv2 makefile

### ISSUE THREAD

**Issue by tidux** [majestrate/nntpchan#148]
In `contrib/backends/srndv2/Makefile`:

```
assert-go:
    test $)VERSION = go1.9Th
```
Not only is this prima facie retarded, it's not even a required check.  The srndv2 binary builds and runs fine with both older (1.7.4) and newer (1.9.1) versions of `go`.  Commenting out the test is sufficient to fix the build process

**Comment by majestrate** [comment]
Yeah that check was for someone else, probably need to remove that now
thnx for reminder

**Comment by majestrate** [comment]
fixed in https://github.com/majestrate/nntpchan/commit/3b83f184eab6b002e7eb3eb177524ac965aa1600
