### ISSUE TITLE
Make a TODO list

### ISSUE THREAD

**Issue by ctrlcctrlv** [majestrate/nntpchan#149]
I'm learning Go for the express purpose of helping this project. What's most important?

**Comment by majestrate** [comment]
frontend templates, css and js needs a good once down. probably most of the work I am not able/willing to do is there.

right now the current state of the backend is in a dire need of a refactor, specifically breaking up the `srnd` package into many smaller decoupled packages.

**Comment by majestrate** [comment]
the srnd package in question is [here](https://github.com/majestrate/nntpchan/tree/master/contrib/backends/srndv2/src/srnd)

**Comment by majestrate** [comment]
I am about to push my TODO file

**Comment by majestrate** [comment]
ohay i already have a [todo file](https://github.com/majestrate/nntpchan/blob/master/TODO.md)

updated.
