### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by sardach** [majestrate/nntpchan#158]
## info

git revision / version: master

OS: Ubuntu 14.04

Architecture: i386

## problem

After web setup i obtain this: ALTER TABLE ArticlePosts ADD COLUMN IF NOT EXISTS frontendpubkey TEXT DEFAULT '': pq: syntax error at or near "NOT"

There are all the logs
~/nntpchan# ./srndv2 setup
2018/06/23 22:02:15 Setting up SRNd base...
2018/06/23 22:02:15 checking for configs...
2018/06/23 22:02:15 No srnd.ini file found in working directory...
2018/06/23 22:02:15 No config file found at ...
2018/06/23 22:02:15 starting installer on :18000
2018/06/23 22:02:15 open up http://youserver:18000/ to do initial configuration
2018/06/23 22:05:21 get locale es
2018/06/23 22:05:24 DB chosen:  postgres
2018/06/23 22:07:13 Cache chosen:  null
2018/06/23 22:07:36 no feeds.ini, creating...
2018/06/23 22:07:36 loading config...
2018/06/23 22:07:36 frontend configured in srnd.ini
2018/06/23 22:07:36 frontend enabled in srnd.ini
2018/06/23 22:07:36 spamd section found
2018/06/23 22:07:36 thumbnails section found
2018/06/23 22:07:36 validating configs...
2018/06/23 22:07:36 configs are valid
2018/06/23 22:07:36 Reading translation files
2018/06/23 22:07:36 get locale en
2018/06/23 22:07:36 connecting to database...
2018/06/23 22:07:36 Connecting to postgres...
2018/06/23 22:07:36 ensure that the database is created...
2018/06/23 22:07:36 set db version to 0
2018/06/23 22:07:36 migrating... 0 -> 1
2018/06/23 22:07:36 set db version to 1
2018/06/23 22:07:36 migrating... 1 -> 2
2018/06/23 22:07:36 set db version to 2
2018/06/23 22:07:36 migrating... 2 -> 3
2018/06/23 22:07:36 set db version to 3
2018/06/23 22:07:36 migrating... 3 -> 4
2018/06/23 22:07:36 migrating post numbers, this can take a bit DO NOT INTERRUPT
2018/06/23 22:07:36 total migrated posts:  0
2018/06/23 22:07:36 set db version to 4
2018/06/23 22:07:36 migrating... 4 -> 5
2018/06/23 22:07:36 set db version to 5
2018/06/23 22:07:36 migrating... 5 -> 6
2018/06/23 22:07:36 set db version to 6
2018/06/23 22:07:37 migrating... 6 -> 7
2018/06/23 22:07:37 set db version to 7
2018/06/23 22:07:37 migrating 7 -> 8
2018/06/23 22:07:37 exec ALTER TABLE ArticleNumbers DROP CONSTRAINT IF EXISTS articlenumbers_message_id_fkey
2018/06/23 22:07:37 exec ALTER TABLE ArticleNumbers ADD CONSTRAINT msgid_depends FOREIGN KEY (message_id) REFERENCES ArticlePosts(message_id) ON DELETE CASCADE
2018/06/23 22:07:37 exec ALTER TABLE NNTPHeaders DROP CONSTRAINT IF EXISTS nntpheaders_header_article_message_id_fkey
2018/06/23 22:07:37 exec ALTER TABLE NNTPHeaders ADD CONSTRAINT msgid_depends FOREIGN KEY (header_article_message_id) REFERENCES ArticlePosts(message_id) ON DELETE CASCADE
2018/06/23 22:07:37 set db version to 8
2018/06/23 22:07:37 ALTER TABLE ArticlePosts ADD COLUMN IF NOT EXISTS frontendpubkey TEXT DEFAULT '': pq: syntax error at or near "NOT"

Help, please

:)))

**Comment by majestrate** [comment]
what version of postgresql are you using?

**Comment by majestrate** [comment]
let me know if this worked and if you need any help
