### ISSUE TITLE
fix thumbnailing more

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#16]
http://oniichanylo2tsi4.onion/thread-f2cfd5d06c.html#f7495e0404eb9950e990c2f8ca10a0e26947e876
http://oniichanylo2tsi4.onion/thread-1f1fb89cdc.html#2f7b24e085c3e1d73e4173ccc273219b8c09f674

no thumbnail

**Comment by majestrate** [comment]
with the first one, mp3 thumbnailings is borked at the moment since sox doesn't read mp3 files. Would need to transcode it to wav then do the thumbnailing on it.

not sure what the second other one was about.

**Comment by majestrate** [comment]
thumbnailing minus .gif should be fixed, .gif is being weird
