### ISSUE TITLE
Fails to create Newsgroups table; ssl not activated on the server...

### ISSUE THREAD

**Issue by anoduck** [majestrate/nntpchan#178]
## info

git revision / version: 1

OS: Both: OpenBSD-6.5 && Ubuntu Disco

Architecture: x86_64

## problem

While setting up srndv2, recieve error that script cannot create the table Newsgroups, because SSL is not enabled on the server. 

SSL is enabled on both servers. Curious if there is another means of creating the needed table and/or loading the database template differently? Regardless, a work around is needed to create the missing table. Is it possible to disable the requirement of SSL on the server? Regardless, cannot run application or progress any further in configuration until this has been successfully achieved.

## backtrace / error messages

Error messages: yes

cannot create table Newsgroups, pq: SSL is not enabled on the server, login was 'user=srnd password='SomePassword' host=127.0.0.1 port=5432 client_encoding='UTF8''

Backtrace: no

How do you switch on debugging for srnd?

**Comment by majestrate** [comment]
On Thu, May 09, 2019 at 01:11:44PM -0700, Anoduck wrote:
> ## info
> 
> git revision / version: 1
> 
> OS: Both: OpenBSD-6.5 && Ubuntu Disco
> 
> Architecture: x86_64
> 
> ## problem
> 
> While setting up srndv2, recieve error that script cannot create the table Newsgroups, because SSL is not enabled on the server. 
> 
> SSL is enabled on both servers. Curious if there is another means of creating the needed table and/or loading the database template differently? Regardless, a work around is needed to create the missing table. Is it possible to disable the requirement of SSL on the server? Regardless, cannot run application or progress any further in configuration until this has been successfully achieved.

try using a socket file instead of a loopback address that may work.

> 
> ## backtrace / error messages
> 
> Error messages: yes
> 
> cannot create table Newsgroups, pq: SSL is not enabled on the server, login was 'user=srnd password='SomePassword' host=127.0.0.1 port=5432 client_encoding='UTF8''
> 
> Backtrace: no
> 
> How do you switch on debugging for srnd?

it does not have a debug mode at this time. so much crap it needs a good refactor but i don't have much time.

**Comment by anoduck** [comment]
Having difficulty getting postgresql to run solely in socket mode in OpenBSD. Going to get Ubuntu configured for socket only, and trying again.

**Comment by anoduck** [comment]
## info

Git revision: 1

OS variety: Ubuntu Disco 

Architecture: Intel x86_64

## problem

In Ubuntu, I get a slightly different error message. The setup script fails to initialize tls. What am I doing or not doing wrong?

## Backtrace / Error Messages

Error Messages: Yes

`failed to initialize tls: open certs/overchan-$HOSTNAME.crt: no such file or directory`

Backtrace: No

Thank you for your help, kindness, time, and contribution.

**Comment by majestrate** [comment]
On Thu, May 09, 2019 at 08:44:23PM -0700, Anoduck wrote:
> ## info
> 
> Git revision: 1
> 
> OS variety: Ubuntu Disco 
> 
> Architecture: Intel x86_64
> 
> ## problem
> 
> In Ubuntu, I get a slightly different error message. The setup script fails to initialize tls. What am I doing or not doing wrong?
> 
> ## Backtrace / Error Messages
> 
> Error Messages: Yes
> 
> `failed to initialize tls: open certs/overchan-$HOSTNAME.crt: no such file or directory`

does a directory called certs exist? if not create it, it should be auto made if it's not that's a bug

**Comment by anoduck** [comment]
EUREKA! Finally! Success. It works!

Thank you, so much.

**Comment by majestrate** [comment]
On Sun, May 12, 2019 at 06:12:13AM +0000, Anoduck wrote:
> EUREKA! Finally! Success. It works!
if you need peering info email me for it.
> 
> Thank you, so much.
yw

**Comment by anoduck** [comment]
Emailed you for peer information, and am I suppose to close the issue or are you? Thanks again.

**Comment by majestrate** [comment]
yeah you can close it if you want
