### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#18]
On a freshly installed debian jessie 8, after building the daemon and configuring the database as instructed, I get the following error:

```
root@localhost:~/local# srndv2 setup
2015/10/20 19:19:54 Setting up SRNd base...
2015/10/20 19:19:54 checking for configs...
2015/10/20 19:19:54 loading config...
2015/10/20 19:19:54 frontend configured in srnd.ini
2015/10/20 19:19:54 frontend enabled in srnd.ini
2015/10/20 19:19:54 validating configs...
2015/10/20 19:19:54 configs are valid
2015/10/20 19:19:54 connecting to database...
2015/10/20 19:19:54 Connecting to postgres...
2015/10/20 19:19:54 ensure that the database is created...
2015/10/20 19:19:54 cannot create table Newsgroups, pq: Peer authentication failed for user "srnd", login was 'user=srnd password=srnd host=/var/run/postgresql port=5432 client_encoding='UTF8''
root@localhost:~/local# 
```

I used the recommended default srnd as password and I don't know why table creation fails. When I try to get to the directory as postgres, I get:

```
cd: /root/local/: Permission denied
or
cd: /root/go/bin/: Permission denied
```

so I assume I am not supposed to be running srndv2 setup as postgres.

postgres seems to be running:
```
anon@localhost:~$ ps -A | grep postgres
27934 ?        00:00:00 postgres
27936 ?        00:00:00 postgres
27937 ?        00:00:00 postgres
27938 ?        00:00:00 postgres
27939 ?        00:00:00 postgres
27940 ?        00:00:00 postgres
anon@localhost:~$ 
```

**Comment by 4cdn** [comment]
Looked into logs, found

```
2015-10-20 19:05:36 EDT [28020-1] srnd@srnd LOG:  provided user name (srnd) and authenticated user name (root) do not match
2015-10-20 19:05:36 EDT [28020-2] srnd@srnd FATAL:  Peer authentication failed for user "srnd"
2015-10-20 19:05:36 EDT [28020-3] srnd@srnd DETAIL:  Connection matched pg_hba.conf line 90: "local   all             all                                     peer"
```
so it seems I neeeeeed to make a srnd user

```
useradd srnd
passwd srnd
mkdir /home/srnd/
chown srnd /home/srnd/
```

srndv2 setup then unsurprising does nothing, not found

okay so

```
root@laptoppc:/home/srnd# go get -u github.com/majestrate/srndv2
bash: go: command not found
```

okay great

```
root@laptoppc:/home/srnd# /root/local/go/bin/go get -u github.com/majestrate/srndv2
go: cannot find GOROOT directory: /usr/local/go
```

and here is where I currently am

**Comment by majestrate** [comment]
you ran some parts as root that were not supposed to be run as root, trying to figure out which ones.

**Comment by 4cdn** [comment]
kk clarify instructions pls cuz it took me two hours

**Comment by majestrate** [comment]
as a rule of thumb, never use root unless you absolutely have to.

**Comment by 4cdn** [comment]
gee thanks

**Comment by majestrate** [comment]
re-ordering the instructions in build.md tell me if they added clarity to the process.

**Comment by 4cdn** [comment]
helps, not much though.

how about suggesting creation of srnd user since the db seems to need same user accessing as what you set, at least mention it there

**Comment by 4cdn** [comment]
running.md could be changed to

set up the daemon, you'll probably want to do this as the same user as you assigned owner of the database:

    srndv2 setup

although I really don't think that's even what you want to do

Most of the stuff not done as root should probably be done as srnd user, database access requires it and for that it seems it needs go set up and configured for srnd user too. That or I suck but I think go needs to be installed and set up as srnd user to work.
