### ISSUE TITLE
autostart script

### ISSUE THREAD

**Issue by adamzend** [majestrate/nntpchan#180]
Can You provide simple example srndv2 autostart script for Debian ?
I'm trying to add it to init.d scripts but doesn't work properly. 
My starting command is : /home/anyuser/nntpchan/srndv2 run > srndv2.out 2>&1. Script is starting but file srndv2.out NOT CREATED. Additionally cannot use /etc/init.d/nntpchan stop . Stopping works only by manually killed process.
Any help ?

**Comment by majestrate** [comment]
i use this systemd unit for my production server
```
[Unit]
Description=NNTPChan Server

[Service]
Type=simple
User=nntpchan
Environment="MAXGOPROCS=4"
WorkingDirectory=/home/nntpchan/nntpchan
ExecStart=/home/nntpchan/nntpchan/srndv2 run
ExecStop=/bin/kill -15 $MAINPID
Restart=always
RestartSec=30s


[Install]
WantedBy=multi-user.target
```

**Comment by adamzend** [comment]
ok. works perfectly. thanks ;-)
