### ISSUE TITLE
Peering with Lynxchan and others

### ISSUE THREAD

**Issue by adamzend** [majestrate/nntpchan#181]
Maybe it is not a typical "issue " but lack of important function and/or informations.

NNTPCHAN is becoming more and more popular. Main network is growing very fast every day. A lot of users planning to transfer their boards from other types of imageboards (especially from Lynxchan)  but there is still no working script that would perform this operation. Also description of how to use it is missing.  In my opinion, such an application that enables communication Lynxchan-> Ntpchan and NNtpchan-> Lynxchan should be done as soon as possible, which will certainly contribute to the further rapid development of network.

regards

**Comment by ctrlcctrlv** [comment]
Imageboards are ephemeral. Software in this space is always changing. Import scripts are, and always have been, a distraction which wastes developer time. Either change software or don't. Make some backups if you want to look back at them some day, or put them through an archive service or two.

**Comment by adamzend** [comment]
I believe that this is not a waste of developer's time but to meet the expectations of  large group of his software users . Of course, everything depends on the author's approach. If he cares about the development of the network he created author should be interested in the expectations of users. Of course, imageboards are ephemaral but the main functions of the sources usually remain the same as in the case of Lynxchan and Nntpchan. Communication between is only small script with protocols translation - nothing more. Its exist but doesn't work and no any description how to use it.

**Comment by ctrlcctrlv** [comment]
If it's such a small script, write it yourself and open a PR. Clearly I don't know anything and you know everything, so why are we even corresponding, again?

**Comment by majestrate** [comment]
we have a shim in vichan but i forget what the status is, importing posts from lynxchan shouldn't be a big problem, going from nntp back to lynxchan is the real issue in this matter.
