### ISSUE TITLE
mod login css

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#19]
seems http://oniichanylo2tsi4.onion/mod/ is sending a get only for http://oniichanylo2tsi4.onion/mod/ and http://oniichanylo2tsi4.onion/static/user.css

http://oniichanylo2tsi4.onion/static/user.css
seems to just be
```
/*
  put your custom stylesheet here
*/
```
perhaps it should be loading site.css instead? would make page purple and stick with the rest of the theme

seems the same for /mod/login too

when not logged in (no nntpchan-mod cookie) /mod/ will load user.css but once logged in and showing you the full mod page /mod/ will load http://oniichanylo2tsi4.onion/static/site.css as I would expect

**Comment by majestrate** [comment]
yeah i probably forgot to add those stylesheets to the templates for those pages

**Comment by majestrate** [comment]
should be fixed in https://github.com/majestrate/nntpchan/commit/e82058d961269f731e9079632585b9725daa34c5
