### ISSUE TITLE
janitor/mod-only boards

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#20]
I don't know how this would actually be done without any scrub being able to peer with a frontend and seeing all the sekrit chats maybe theirs a way to encrypt messages to a certain list of pubkeys idk i know u can with pgp

i dont think im serious ill close this in a hour maybe

also tell me ur new pubkey for "full list of nntpchan frontends"

**Comment by majestrate** [comment]
we can do encryption with the mod keys we have already, this is an interesting idea, mod PMs
