### ISSUE TITLE
captcha background

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#24]
/contrib/static/site.css has captcha background set twice

lines 119-121
```
#captcha_img {
    background: #d3d3d3;
}
```
lines 253-255
```
#captcha_img {
    background: grey;
}
```

also its set twice in dank branch just different values

**Comment by majestrate** [comment]
css is hard D:

**Comment by majestrate** [comment]
https://github.com/majestrate/nntpchan/commit/1614cef91fd2262c06c52fa02da1c5312e8d81d3 should have fixed it
