### ISSUE TITLE
filename field

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#25]
when posting, if you select an attachment with a long filename, the size of the postform will increase, but the size of the field displaying the filename won't increase

selecting a short filename has no effect on the post field

**Comment by 4cdn** [comment]
this is what i mean http://oniichanylo2tsi4.onion/img/IEEGDEKTIT5DYRWKSWUAXC5NHXYZKEBHTBE54DZK5YGIBQSGDIUYII4BX2WSDVIYB7GH3LEU62HFK37O3FC4XIZOGMHN6MJ23DQ6FMY=.PNG

**Comment by viniciusbo** [comment]
What browser are you using? Couldn't reproduce that on Chrome.

**Comment by majestrate** [comment]
Probably either Tor Browser or another Firefox derivative.

**Comment by 4cdn** [comment]
ff42-20151029151421, seems fixed
