### ISSUE TITLE
psy is broke

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#30]
probably from the ```<p> to <br>``` change and because

```
.psy > p {
```
doing just .psy makes a vertical area larger than one line light up

```
<label class="post_body">
    <span class="psy">tost <br><br></span><br>
  </label>
```
those two br that are inside the span probably shouldnt be but for uniformity you would want them all together unless it actually serves your purposes

**Comment by majestrate** [comment]
fixed in https://github.com/majestrate/nntpchan/commit/c23696aae5aec0e40f006a777fe2c6e7ce93c92e
