### ISSUE TITLE
code tag adds unwanted newline

### ISSUE THREAD

**Issue by chen-chan** [majestrate/nntpchan#41]
```
[code]
stuff
stuff
[/code]
```
this results in 2 newlines before \<pre\> tag ends. not sure how to deal with that though. can be prevented by putting `[/code]` right after the code but most people probably won't do that.

one solution i got is using \<code\> or \<span\> tag instead and adding the \<br\>s. kinda like quotes work.

**Comment by majestrate** [comment]
so 

    [code]
    stuff1
    stuff2
    [/code]

should yield

    <pre>stuff1
    stuff2</pre>

not 

    <pre>

    stuff1
    stuff2
    </pre>

correct?

**Comment by majestrate** [comment]
code tags are hard D:

they have been removed for now
