### ISSUE TITLE
setting custom template dir doesn't work

### ISSUE THREAD

**Issue by chen-chan** [majestrate/nntpchan#42]

**Comment by 4cdn** [comment]
did u check yo dir/file permissions fool

**Comment by chen-chan** [comment]
same owner and permissions with the default. 

srnd.ini:
```
[frontend]
templates=contrib/templates/my-template
```
it just uses the default. does it work _for you_?

inb4 i'm idiot and it's something trivial

**Comment by majestrate** [comment]
the template directory is actually hard coded right now so changing the
config values doesn't do anything, ima get coffee first so i can fix this

**Comment by chen-chan** [comment]
if u fix it that means i can just git pull my templates without shutting down the server and lose precious posts (them instantly syncing at least) becuse it's like https://github.com/chen-chan/nntpchan/tree/chen-chan

btw we peered it was a bit lewd tbh :3 
http://ucavviu7wl6azuw7.onion
http://104.238.229.158:18000

**Comment by majestrate** [comment]
commit 4911dbc contains initial wack at fix

**Comment by majestrate** [comment]
rather, https://github.com/majestrate/srndv2/commit/4911dbcc9c287467b7bb79d5103d0fb5ccf643f1

**Comment by chen-chan** [comment]
do i just /build.sh again to update binaries?

**Comment by majestrate** [comment]
yes

**Comment by chen-chan** [comment]
it werkd [tapu tapu tapu] thx qt.
>tfw no sage to not bother with
they should have just embedded a chan tbh smh fam.
