### ISSUE TITLE
More translations

### ISSUE THREAD

**Issue by majestrate** [majestrate/nntpchan#49]
Internationalization support was added recently.

We have so far:
- English
- German
- Spanish
- Russian
- Portuguese

Translations into other languages desired including:
- Mandarin
- ~~Spanish~~
- ~~Russian~~
- French
- ~~Portuguese~~
- Japanese
- Polish

Those are just the languages that I can name off the top of my head on a sunday at 9am but any other language translations would be great.

**Comment by majestrate** [comment]
Spanish added

**Comment by majestrate** [comment]
Portuguese added

**Comment by majestrate** [comment]
Russian Added

**Comment by deavmi** [comment]
You need Afrikaans? XD

**Comment by deavmi** [comment]
I know a tad of french but I don't know if it could be helpful.
