### ISSUE TITLE
.ico thumbnailing

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#5]
implement .ico thumbnailing

i mean you sperged out and did audio thumbnailing so

**Comment by majestrate** [comment]
Does .ico thumbnailing not work? It SHOULD work.

**Comment by 4cdn** [comment]
http://oniichanylo2tsi4.onion/thread-6906ef59ee.html
post 4cccc36019

**Comment by majestrate** [comment]
should be fixed in srdnv2 https://github.com/majestrate/srndv2/commit/433ffdda86eb5f28d2279e29826f2bb9adfb0df3
