### ISSUE TITLE
General Overview Infographic

### ISSUE THREAD

**Issue by majestrate** [majestrate/nntpchan#50]
To boost popularity I guess we'd need a document/infographic that explains/overviews nntpchan, what it is, what it isn't, what it does, what it doesn't do, what it could be, all for a non technical audience.

**Comment by deavmi** [comment]
I could write something for this. Let's close this issue by doing so! :)

**Comment by deavmi** [comment]
I will try so this this week. Maybe Friday.

**Comment by deavmi** [comment]
Can a node choose which groups are synced with which nodes. Or is it which groups are synced (with all nodes) and which are not?

**Comment by deavmi** [comment]
So far I have this:

````
NNTPChan is a decentralized discussion board which has the ability to sync posts on certain groups with other NNTPChan nodes. The syncing of posts is done via the NNTP protocol and uses public-key encryption when transferring data with a node. Every NNTPChan node can create their own groups for discussion on certain topics and choose which ones (or all) they would like to sync with the nodes they are connected to (peered with) and which groups are not to be synced with other nodes.
````
