### ISSUE TITLE
redis instructions create configs first

### ISSUE THREAD

**Issue by chen-chan** [majestrate/nntpchan#53]
At nntpchan/doc/redis.md, shouldn't we create a srnd.ini with `./srndv2 setup` first before modifying the db section?

**Comment by chen-chan** [comment]
in fact `./srndv2 setup` fills db section correctly itself.

**Comment by majestrate** [comment]
latest revisions default to redis because postresql is harder to do right. the redis defaults should work despite the errors in generated configs.

**Comment by deavmi** [comment]
Is this done yet?

**Comment by majestrate** [comment]
redis is `DEPRECATED` :^)

**Comment by deavmi** [comment]
Okie dokie. :)
