### ISSUE TITLE
>implying apt-get has the latest versions

### ISSUE THREAD

**Issue by wzeth** [majestrate/nntpchan#55]
I preface this by saying that it's the user's responsibility to know what they are installing.

That being said, it would have been a little easier to install had I known that the default Debian repos do not have the required version of golang or redis-server.

I think others might benefit from an addendum that, by default, Debian (and probably others) will not have the required versions.

**Comment by majestrate** [comment]
so the documentation does not reflect what the install process should be?

**Comment by majestrate** [comment]
docs should be more up to date as of https://github.com/majestrate/nntpchan/commit/bc239360eacfce963794c1f590eb601b41f3b36c

**Comment by wzeth** [comment]
That addresses it. Thank you.
