### ISSUE TITLE
looking in invalid directory for site.css

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#7]
in /contrib/templates/default/post_fail.mustache

`<link rel="stylesheet" href="{{prefix}}static/site.css"></link>`

but since browser posts to http://site.tld/post/overchan.test

browser will try to load

/post/static/site.css

but content is in /static/site.css

probably a couple of the .mustache files have this issue

which is why the captcha failed page hurts my eyes :/

**Comment by majestrate** [comment]
forgot to pass in a parameter when rendering templates 
probably fixed in https://github.com/majestrate/srndv2/commit/e8ad070534eed2122167eed137422985aed97717

**Comment by majestrate** [comment]
is it fixed on your end?

**Comment by 4cdn** [comment]
Yes.
