### ISSUE TITLE
My wishes.

### ISSUE THREAD

**Issue by deavmi** [majestrate/nntpchan#72]
This is not generally asking @majestrate but anyone who can do the following:
- A professional looking theme (like Bootstrap - that doesn't look like it came from the shithole that is `chan*`.
- Easier way to configure feeds (also easier docs)
- Better configuration panel
- Better configuration file (with comments)
- Remove the old NNTP (2nd server) from the config file.

**Comment by majestrate** [comment]
> bootstrap theme
yes that would be nice

> easier feed configuration
agree, needs more detail

> better config panel
agree, also needs more detail, better in what way?

> better config files (with comments)
agree

>remove old nntp option
agree

**Comment by deavmi** [comment]
"agree, also needs more detail, better in what way?" Rename the parameter names, they could be way better. Don't abbreviate and if you need to then use a comment to explain what that parameter does and it's states (0or 1)

**Comment by deavmi** [comment]
@psgs Could you help with a Bootstrapped or your own professional looking theme for this project?

**Comment by psgs** [comment]
Hello :smiley: 

Although this seems like an awesome project, and I would love to help, I'm a bit too busy with exams at the moment. Sorry :confused:

**Comment by deavmi** [comment]
Don't wory man. :)

Also busy with exams. :)

On 05 June 2016 3:21:09 AM SAST, Francois <notifications@github.com> wrote:
>Hello :smiley: 
>
>Although this seems like an awesome project, and I would love to help,
>I'm a bit too busy with exams at the moment. Sorry :confused: 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/majestrate/nntpchan/issues/72#issuecomment-223787489

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deavmi** [comment]
I'm going to see if I can some how imporve the current mod panel with some h1 etc. tags

**Comment by deavmi** [comment]
Assuming to amke a title such as `<h1>Mod pannel</h1>` I would do
 `<h1>{{#i18n.Translations}}{{mod_pannel_page_heading}}{{/i18n.Translations}}</h1>`

**Comment by deavmi** [comment]
I wanted to know. About the whole thing of the NNTP server and that clients can spam. Should there maybe be a limit on how many posts can be made from an NNTP client.

This would probably mean that two NNTP servers should run.

The first NNTP server for the actual message propagation. (The one that talks to other Chan's)

And the second NNTP server for clients to connect to.

**Comment by majestrate** [comment]
>Should there maybe be a limit on how many posts can be made from an NNTP client.

possibly but it's always possible to "fake" a few things with the current sync stuff. you could always pretend to be another nntp server instead of a newsreader that posts.

I am of the opinion that IP based limits are futile in the long run.
