### ISSUE TITLE
GNU AGPL?

### ISSUE THREAD

**Issue by deavmi** [majestrate/nntpchan#75]
Ever thought of using the GNU AGPL? So that forks of your projetc must open source their code and if someone runs a modified NNTPChan node they must open source their changes as well?

**Comment by majestrate** [comment]
I personally dislike the virility clauses in GPL3 which is why I have chosen MIT/X11.

**Comment by deavmi** [comment]
Okay :smile:

**Comment by deavmi** [comment]
Whart does "virility" mean?

**Comment by majestrate** [comment]
i used the wrong word here.

what I meant to say is that I dislike AGPL's viral properties, specifically how GPL 3 code cannot be used in non GPL 3 licensed code.

**Comment by deavmi** [comment]
Oh really.

**Comment by deavmi** [comment]
I wish license writing could be easy. So that everyone could make a license that suits their needs.
