### ISSUE TITLE
failing captcha on board creation

### ISSUE THREAD

**Issue by 4cdn** [majestrate/nntpchan#9]
failing captcha on new board creation sends you to http:///

http://oniichanylo2tsi4.onion/post/overchan.dankspacejams
`
<html>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="/static/site.css"></link>
  <meta http-equiv="refresh" content="1; //" />
  <body>
    <p>post failed: failed captcha. no captcha.</p>
  </body>
</html>
`

also it sends you to a 404 page when you dont have js enabled

maybe default nginx config should have 404 page as

"404 page not found

enable javascript and try again?"

or maybe make a /post/index.html that says enable js and try again

**Comment by 4cdn** [comment]
also creation of a new board sets no subject and poster name as the board name

why?

also its dank you can post to existing boards with no subject instead of None

**Comment by 4cdn** [comment]
editing the reference value also redirs to http:/// after posting

`
<html>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="/static/site.css"></link>
  <meta http-equiv="refresh" content="1; //" />
  <body>
    <p>post failed: invalid reference: BENISBENISBENISBENISBENISBENISBENISBENIS, not posting. </p>
  </body>
</html>
`

**Comment by 4cdn** [comment]
because of the no subject or weird poster name it doesn't show that thread on lolz2

http://lyp6sf5tzd6mbnmc.onion/dankspacejams-1.html

that or sync is fugt

**Comment by majestrate** [comment]
I think it's probably sync again

**Comment by 4cdn** [comment]
still can't see "second best" thread on lolz2, seems the lack of subject is keeping it from showing

**Comment by majestrate** [comment]
it seems what happened is that because the subject was not provided in the article header and was considered invalid by lolz, same happens with no name field because then it doesn't generate a message-id
trying fix in https://github.com/majestrate/srndv2/commit/aa7c09f116cef249b3babfd18ee918f8e0e881f0

**Comment by 4cdn** [comment]
do you get the redir to http:/// on entering an incorrect captcha when using the new board creation page?

**Comment by majestrate** [comment]
i'll test that one now

**Comment by majestrate** [comment]
I do, i'll fix that

**Comment by majestrate** [comment]
latest commit probably fixed it.
try it.

**Comment by 4cdn** [comment]
seems fixed.
